<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
    <Folder Include="Identity\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.27" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIResumeAnalyzer.Application\AIResumeAnalyzer.Application.csproj" />
    <ProjectReference Include="..\AIResumeAnalyzer.Domain\AIResumeAnalyzer.Domain.csproj" />
  </ItemGroup>

</Project>
