<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Commands\Login\" />
    <Folder Include="Features\Auth\Validators\" />
    <Folder Include="Features\Interview\" />
    <Folder Include="Features\JobMatching\" />
    <Folder Include="Features\Resume\Commands\" />
    <Folder Include="Features\Resume\DTOs\" />
    <Folder Include="Features\Resume\Validators\" />
    <Folder Include="Features\Resume\Queries\" />
    <Folder Include="Interfaces\IRepository\" />
    <Folder Include="Interfaces\IAIService\" />
    <Folder Include="Interfaces\IFileService\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIResumeAnalyzer.Domain\AIResumeAnalyzer.Domain.csproj" />
  </ItemGroup>

</Project>
